fix: update type error in template code
windingwind/zotero-plugin-template pull request #27
Opened 2023-03-03 01:49 UTC by l0o0

Fix type error in template [examples.ts](https://github.com/windingwind/zotero-plugin-template/blob/bootstrap/src/modules/examples.ts)

2023-03-03 02:42 UTC, volatile-static requested changes

2023-03-03 02:42 UTC, volatile-static commented on src/modules/examples.ts
> +        addon.hooks.onNotify(event, type, ids as string[], extraData);
这里或许存在number的情况？

2023-03-03 06:35 UTC, l0o0 commented on src/modules/examples.ts
> +        addon.hooks.onNotify(event, type, ids as string[], extraData);
> 这里或许存在number的情况？

听你这么一说，我感觉知道怎么改了

2023-03-04 01:11 UTC, volatile-static requested changes

2023-03-04 01:11 UTC, volatile-static commented on src/hooks.ts
> +  ids: Array<string> | Array<number>,
```suggestion
  ids: Array<string | number>,
```

2023-03-12 16:23 UTC, merged