feat: add chinese readme document
windingwind/zotero-plugin-template pull request #75
Opened 2023-11-11 13:52 UTC by KikkiZ

The Chinese version of the readme document was added, and the corresponding link was added in the original document

2023-11-11 14:18 UTC, windingwind requested changes

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +  > 不要中断 `prefs.js`
机翻痕迹

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +- 广泛骨架下的事件驱动、函数式编程；
广泛骨架 - 表达比较奇怪

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +- ⭐[新!]自动热重载！每当修改源码时，都会自动翻译并重新加载；[详情请跳转→](#auto-hot-reload)
自动翻译 - 表达奇怪

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +  - 对整个Zotero项目的完整类型定义支持，并且使用 JavaScript 编写 (使用的类型定义[zotero-types](https://github.com/windingwind/zotero-types))；
语义错误

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +### 提示示例(PromptExamples)
`Prompt`翻译为`提示`似不妥

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +> 该库构建好的xpi文件不承诺任何实际功能，它可能不是最新的版本.
机翻痕迹

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +   > (可选项) 此操作仅需执行以此: 使用 `/path/to/zotero -p` 启动 Zotero，创建一个新的配置文件并用作开发配置文件.
笔误

2023-11-11 14:18 UTC, windingwind commented on readme/README.zh-CN.md
> +### 自动热加载(Auto Hot Reload)
名词前后一致

2023-11-11 14:21 UTC, windingwind commented
感谢贡献。一些小问题已在上面回复。
在决定是否合并之前，我希望了解您对未来主readme产生更新时，及时PR对应中文版进行跟进PR的意愿/能力。如果您难以保证持续相当长一段时间内能够及时对主readme的更新，尤其是重要更新，进行响应，我可能不会考虑合并 - 因为最终会变成我需要额外维护一份（我自己都不使用的）文档。

2023-11-13 06:03 UTC, KikkiZ commented
> 感谢贡献。一些小问题已在上面回复。 在决定是否合并之前，我希望了解您对未来主readme产生更新时，及时PR对应中文版进行跟进PR的意愿/能力。如果您难以保证持续相当长一段时间内能够及时对主readme的更新，尤其是重要更新，进行响应，我可能不会考虑合并 - 因为最终会变成我需要额外维护一份（我自己都不使用的）文档。

我会在收到更新通知时尽可能及时更新文档，不过我不能保证在文档更新的很短时间（几小时）内同步更新，但我会在文档更新的几天或一周内同步。
上面的翻译问题已经尽可能修改了，有一些地方还存在一些疑惑，因为原文表达的意思我不太理解。我尽可能通过网络搜索相关的内容，按照我的理解进行翻译了一次，但可能依然存在一些问题。如果翻译还存在错误，我会尽快修改

2023-11-13 06:24 UTC, windingwind commented
感谢贡献。我有空的时候再小作修改即可合并
不需要快速响应所有修改。如果有较大变动需要同步，我会开一个issue并assign给你，几天/一两周内有空回应即可

2023-11-13 08:37 UTC, merged