fix: esbuild breaks server
windingwind/zotero-plugin-template pull request #94
Opened 2023-12-28 12:27 UTC by northword

2024-01-05 11:08 UTC, volatile-static requested changes

2024-01-05 11:08 UTC, volatile-static commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
是我没读懂吗，怎么感觉第一次调用就会延迟1秒，然后同时调用10次的话他会分10秒执行10次呢

2024-01-05 11:27 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
第一次执行确实会延迟1秒，这个我觉得影响不大，后半句似乎并不会

![image](https://github.com/windingwind/zotero-plugin-template/assets/44738481/68ca5e6c-cae0-4888-94ce-c90709b2ef31)

2024-01-05 11:29 UTC, volatile-static commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
嗯，影响确实不大，但感觉不合理啊，建议换个思路

2024-01-05 11:31 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
啊  具体哪里不合理呢，没闭包？

2024-01-05 12:04 UTC, volatile-static commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
我觉得一个常见的消抖逻辑应该是：首次触发时立即执行，第二次触发时判断与上一次的时间差

2024-01-05 13:54 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
> 我觉得一个常见的消抖逻辑应该是：首次触发时立即执行，第二次触发时判断与上一次的时间差

我觉得你说的这个更接近节流 throttle 而不是防抖 debounce？（我确实不了解这个，纯靠 google）

2024-01-05 14:07 UTC, volatile-static commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
没必要深究概念性的问题。我想表达的意思是，在这种场景下，首次调用立即触发更合理

2024-01-05 14:15 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
我觉得末次调用更合理，多次操作应该用最后一次的编译结果重载。

2024-01-05 14:46 UTC, volatile-static commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
对于减少依赖包的观点，你和winding是有共识的。虽然我持保留意见，但我想目前这个问题是：引入新的庞大依赖与引入简短的低质量代码哪个更不利于维护

2024-01-05 15:03 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
> 哦确实，是我刚才理解错了。这种情况应该更符合你刚才说的debounce。所以我的建议是采用lodash库，而不是每次都-1s🤓

lodash 也是通过 timeout，基本逻辑是类似的（吧）

2024-01-05 15:04 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
> 对于减少依赖包的观点，你和winding是有共识的。虽然我持保留意见，但我想目前这个问题是：引入新的庞大依赖与引入简短的低质量代码哪个更不利于维护

也许要看“简短的低质量代码”的质量到底有多低？

2024-01-05 16:12 UTC, windingwind commented on scripts/server.mjs
> +  execSync(command, { timeout: 8000 });
这里的8000是什么意思呀

2024-01-05 16:12 UTC, windingwind commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
我大致理解了一下，这里的代码复杂度不是很高，用timeout实现基本上也很难再简单了，我觉得问题不大；如果嫌嵌套层级太多可以单独独立出来一个函数处理这部分延迟的逻辑。至于首次或末次是否延迟1s我感觉不是很要紧。

另外想讨论一下是否用延迟重载直到下一次窗口获得焦点比较好？因为我全屏vscode开发的时候，一旦编译-触发重载，就会聚焦zo的窗口，导致还得手动切换回vscode，有点麻烦

2024-01-06 00:56 UTC, northword commented on scripts/server.mjs
> +  execSync(command, { timeout: 8000 });
即使前面已经加了1s，但是连续多次reload仍会导致zo崩溃（我猜是reload用时不止1s导致的），所以给reload加了个超时，8s后reload仍然没有结束，那基本上就是zo已经未响应了，这时候直接结束进程

2024-01-06 00:58 UTC, northword commented on scripts/server.mjs
> +      // debounced, see https://github.com/samhuk/chokidar-debounced/blob/master/index.ts
获取焦点后再重载这个有可能对多屏开发的不方便了？也许加个选项？ 😂
而且我们可以在脚本内获取到这个焦点事件嘛？

2024-01-06 02:11 UTC, volatile-static commented
关于消抖的方案，我有一个新的想法：对于高并发重载采取触发两次的策略，第一次触发后立即执行，若后续触发间隔小于timeout，则等待2个timeout后再触发一次。

关于焦点的方案，我觉得只能开一个真正的server了，插件的toolkit注册onFocus事件，然后doPost到node server

2024-01-06 02:58 UTC, windingwind commented
> 关于焦点的方案，我觉得只能开一个真正的server了，插件的toolkit注册onFocus事件，然后doPost到node server

也许不需要这么复杂，在插件/工具箱代码里写入控制重载触发的代码；重载时传入参数负责通知发生重载即可。具体控制逻辑可在插件代码完成

2024-01-06 07:38 UTC, northword commented
话说，toolkit 有没可能把开发相关的脚本也加进去呢？类似 https://github.com/retorquere/zotero-plugin 那样的，或者新开一个包，

通过 `.env` 包读取现 `zotero-cmd.json` 里的东西，把 start.mjs / server.mjs / build.mjs / release 都包括进去，这样多插件的开发者以后更新起来可能会比较方便；
目前插件模板的结构与 retorquere 的差别比较大，所以 zotero-plugin 对插件模板这样结构的不太友好，而且他那个发布流程是基于分支的，对比咱们现有的比较复杂。

2024-01-06 07:42 UTC, windingwind commented
可以单独开一个包；但是考虑到现在和toolkit功能上的依赖，也可以放在toolkit里面，有啥想法考虑？

2024-01-06 13:11 UTC, northword commented
按照群里的讨论，使用 `web-ext` 作为 reload 方法的：

```js
// server.mjs
import { main as build, esbuildOptions } from "./build.mjs";
import { openDevToolScript, reloadScript } from "./scripts.mjs";
// import { main as startZotero } from "./start.mjs";
import { Logger } from "./utils.mjs";
import cmd from "./zotero-cmd.json" assert { type: "json" };
import { execSync } from "child_process";
import chokidar from "chokidar";
import { context } from "esbuild";
import path from "path";
import { exit } from "process";
import webExt from "web-ext";

process.env.NODE_ENV = "development";

const { zoteroBinPath, profilePath } = cmd.exec;

const startZoteroCmd = `"${zoteroBinPath}" --debugger --purgecaches -profile "${profilePath}"`;

async function watch() {
    const watcher = chokidar.watch(["src/**", "addon/**"], {
        ignored: /(^|[\/\\])\../, // ignore dotfiles
        persistent: true,
    });

    const esbuildCTX = await context(esbuildOptions);
    let currentTimeout = null;

    watcher
        .on("ready", () => {
            Logger.info("Server Ready! \n");
        })
        .on("change", async (path) => {
            Logger.info(`${path} changed at ${new Date().toLocaleTimeString()}`);

            async function rebuild() {
                if (path.startsWith("src")) {
                    await esbuildCTX.rebuild();
                } else if (path.startsWith("addon")) {
                    await build();
                }
            }

            clearTimeout(currentTimeout);
            currentTimeout = setTimeout(async () => {
                await rebuild().catch((err) => {
                    Logger.error(err);
                });
            }, 1000);
        })
        .on("error", (err) => {
            Logger.error("Server start failed!", err);
        });
}

async function startWebExt() {
    await webExt.cmd.run(
        {
            // These are command options derived from their CLI conterpart.
            // In this example, --source-dir is specified as sourceDir.
            firefox: zoteroBinPath,
            firefoxProfile: profilePath,
            sourceDir: path.resolve("build/addon"),
            keepProfileChanges: true,
            // browserConsole: true,
        },
        {
            // These are non CLI related options for each function.
            // You need to specify this one so that your NodeJS application
            // can continue running after web-ext is finished.
            shouldExitProgram: false,
        },
    );
}

// function reload() {
//     Logger.debug("Reloading...");
//     const url = `zotero://ztoolkit-debug/?run=${encodeURIComponent(reloadScript)}`;
//     const command = `${startZoteroCmd} -url "${url}"`;
//     execSync(command, { timeout: 8000 });
// }

function openDevTool() {
    Logger.debug("Open dev tools...");
    const url = `zotero://ztoolkit-debug/?run=${encodeURIComponent(openDevToolScript)}`;
    const command = `${startZoteroCmd} -url "${url}"`;
    execSync(command);
}

async function main() {
    // build
    await build();

    // start Zotero
    await startWebExt();

    // setTimeout(() => {
    //     openDevTool();
    // }, 5000);

    // watch
    await watch();
}

main().catch((err) => {
    Logger.error(err);
    // execSync("node scripts/stop.mjs");
    exit(1);
});

process.on("SIGINT", (code) => {
    execSync("node scripts/stop.mjs");
    Logger.info(`Server terminated with signal ${code}.`);
    exit(0);
});

```

原 start.mjs 基本上可以删除了；reload 时候不会强行聚焦到 Zotero 窗口。

存在以下问题：

1. 无法启动 devtool

  - 现有的启动 devtool 的方式会提示：
    
    ![image](https://github.com/windingwind/zotero-plugin-template/assets/44738481/20d59bee-ac78-484e-a5f0-4574c27cce14)

  - 等 Zotero 升级到 Firefox 115，就可以通过 web-ext 的 `--devtool` 来打开 


2. 无法结束 server

`ctrl+c` 结束任务时，无法正常退出，这可能需要其他地方修改。

![image](https://github.com/windingwind/zotero-plugin-template/assets/44738481/ec63b635-47e8-45ef-b7ed-428537286b26)

3. reload 后，插件原有的窗口需要重新手动打开（比如首选项窗格的 buildTime 并不会自动刷新，而是需要重新打开后才能看到新的），重载前插件创建的弹窗等也需要手动关闭（原来的 reload 方法会自动关闭所有的弹窗和首选项）。

我感觉我有点不太能解决，先贴出来八

2024-01-06 13:57 UTC, windingwind commented on addon/manifest.json
> +    "gecko": {
话说这个有必要吗

2024-01-06 13:57 UTC, windingwind commented on scripts/server.mjs
> +  await startWebExt();
也许可以尝试spawn或者子进程打开web-ext，不使用脚本调用，以控制程序正常退出

2024-01-06 13:58 UTC, windingwind commented
新的改动后，我似乎无法正常重载插件模板-正常重载会启动时打开那个窗口

如果结束时没有关闭窗口，则可能插件未正常终止。

2024-01-06 13:58 UTC, northword commented on addon/manifest.json
> +    "gecko": {
是必须的，否则 web-ext 会报错 缺少   applications.gecko

2024-01-06 14:04 UTC, northword commented
> 正常重载会启动时打开那个窗口

~~是指那个 progressWindow 吗？这个是没有的~~

插件模板的那个示例弹窗？初次启动可以正常打开，重载后没有弹出，但是重载后首选项里的buildTime是变了的，有点奇怪

2024-01-06 14:13 UTC, windingwind commented
这个报错习以为常了，打开控制台就会有。应该是插件资源重载了，但是没有调用对应的钩子 - 对应钩子是zotero里面定义的，可能要翻下源码，由z支持才行

2024-01-06 14:37 UTC, windingwind commented
还有个问题，6100远程连接连不上了，不知道是因为端口占用还是什么别的缘故

2024-01-07 07:14 UTC, windingwind commented
可以暂时挂起，等z方面支持了再考虑合并

2024-03-31 06:45 UTC, closed without merging

2024-03-31 06:45 UTC, northword commented
Suppressed by #109